@startuml class-fhx

class FHXFile{
    FHXItem[] items
}

class FHXItem{
    FHXItem parent
    FHXItem[] children
}

class FHXParameter{
    FHXItem parent
}

class Tokenizer{
    next()
    peek()
    eof()
}

class FHXParser{
    FHXFile parse(file)
}

class Token{
    string data
    TokenType type
}

class StreamReader{
    next()
    peek()
    eof()
}

enum TokenType{
    OPEN_BRACKET
    CLOSE_BRACKET
    STRING
    VALUE
    EQUAL
    COMMENT_START
    COMMENT_END
}

FHXFile *-- FHXItem
FHXItem *-- FHXParameter

FHXParser *-- FHXFile
FHXParser *-- Tokenizer
Tokenizer *-- Token
Token *-- TokenType
Tokenizer *-- StreamReader

@enduml